config/routes.rb
Rails.application.routes.draw do

  get 'google_login_api/callback'
  get 'password_resets/new'
  get 'password_resets/create'
  get 'password_resets/edit'
  get 'password_resets/update'
  root "static_pages#top"
 
  resource :session, only: [:new, :create, :destroy]
  get '/auth/:provider/callback', to: 'sessions#google_oauth2'
  get '/auth/failure', to: redirect('/')
  resources :static_pages, only: %i[new create show edit update destroy] do
end
  resources :users, only: [:new, :create, :show, :edit, :update]
  resources :boards do
    resources :comments, only: [:create, :update, :destroy]
  end
  resources :password_resets, only: %i[new create edit update]
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  delete 'logout', to: 'sessions#destroy'
  post '/google_login_api/callback', to: 'google_login_api#callback'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.8.1/font/bootstrap-icons.min.css">
    
    <title><%= content_for?(:title) ? yield(:title) : "LOL TeamFinder" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- OGP Meta Tags -->
    <meta property="og:title" content="LOL TeamFinder" />
    <meta property="og:description" content="LOL TeamFinderで仲間を見つけよう！" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:type" content="website" />
    <meta property="og:site_name" content="LOL TeamFinder" />

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbo-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
  </head>

  <body>
  <header>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <%= link_to 'ホーム', root_path, class: 'navbar-brand' %>
      
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ms-auto">
          <% if logged_in? %>
            <li class="nav-item">
              <%= link_to current_user.name, user_path(current_user), class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'ログアウト', logout_path, method: :delete, data: { turbo_confirm: 'ログアウトしますか？' }, class: 'nav-link' %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to 'ログイン', new_session_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to '新規登録', new_user_path, class: 'nav-link' %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>


<% if flash.any? %>
    <div id="flash-messages">
      <% flash.each do |type, message| %>
        <div class="flash <%= type %>"><%= message %></div>
      <% end %>
    </div>
  <% end %>

    <%= yield %>
  </body>
</html>